.globals: &globals
  tags:
  - python

variables:
  PROJECT_NAME: "drace-gui"
  GIT_SUBMODULE_STRATEGY: "normal"

stages:
  - test

python:
  stage: test
  script:
  - echo "Start test..."
  - python3 drace-gui.py