.globals: &globals
  tags:
  - windows
  - dynamorio

.testing: &testing
  variables:
    GIT_STRATEGY: "none"


variables:
  PROJECT_NAME: "DRace"
  GIT_SUBMODULE_STRATEGY: "normal"
  DRRUN_EXE: "C:\\opt\\DynamoRIO-Windows-7.91.18081-0\\bin64\\drrun.exe"
  _NT_SYMBOL_PATH: "SRV*c:\\symbolcache\\*https://msdl.microsoft.com/download/symbols"
stages:
  - generate
  - validate
  - build
  - test
  - gui-test
  - package

cmake:
  <<: *globals
  stage: generate
  script:
  - echo "Release build..."
  - .\contrib\generate-ci.bat
  except:
    changes:
    - tools/drace-gui/**/*
  artifacts:
    paths:
    - build-tsan-dr791
    - build-legacy-tsan-dr791
    - build-dummy
        
compile:
  <<: *globals
  stage: build
  except:
    changes:
    - tools/drace-gui/**/*
  except:
  - doc-*
    
  script:
  - echo "Release build..."
  - .\contrib\build-ci.bat
  artifacts:
    paths:
    - build-tsan-dr791
    - build-legacy-tsan-dr791
    - build-dummy
  dependencies:
  - cmake

cppcheck:
  <<: *globals
  stage: validate
  except:
    changes:
    - tools/drace-gui/**/*
  script:
  - cd build-tsan-dr791;  C:\opt\Cppcheck\cppcheck.exe  --project=compile_commands.json --enable=all --inline-suppr --suppressions-list=suppressions.txt --error-exitcode=1 --quiet
  - cd ../build-legacy-tsan-dr791;  C:\opt\Cppcheck\cppcheck.exe  --project=compile_commands.json --enable=all --inline-suppr --suppressions-list=suppressions.txt --error-exitcode=1 --quiet
  - cd ../build-dummy; C:\opt\Cppcheck\cppcheck.exe  --project=compile_commands.json --enable=all --inline-suppr --suppressions-list=suppressions.txt --error-exitcode=1 --quiet
  dependencies:
  - cmake

#
# Test all builds
#

test-tsan-dr791:
  <<: *globals
  <<: *testing
  stage: test
  except:
    changes:
    - tools/drace-gui/**/*
  script:
  - cd build-tsan-dr791
  - echo "Use DR 7.91.x"
  - .\test\drace-tests.exe --dr $env:DRRUN_EXE --gtest_output="xml:test-results.xml"
  artifacts:
    reports:
      junit:
      - build-tsan-dr791\test-results.xml
  dependencies:
  - compile


test-tsan-dr791-legacy:
  <<: *globals
  <<: *testing
  stage: test
  except:
    changes:
    - tools/drace-gui/**/*
  script:
  - cd build-legacy-tsan-dr791
  - echo "Use DR 7.91.x (LEGACY build)"
  - .\test\drace-tests.exe --dr $env:DRRUN_EXE --gtest_output="xml:test-results.xml" --gtest_filter="-DrIntegration*.DotnetClr*"
  artifacts:
    reports:
      junit:
      - build-legacy-tsan-dr791\test-results.xml
  dependencies:
  - compile


gui-test:
  stage: test 
  tags: 
  - AWS
  only:
    changes:
    - tools/drace-gui/**/*
    - .gitlab-ci.yml
  script:
  - echo "Start test..."
  - python3 tools/drace-gui/draceGUI.py --Debug
  - python3 tools/drace-gui/draceGUIUnitTest.py
  

# Package

bundle:
  <<: *globals
  stage: package
  except:
    changes:
    - tools/drace-gui/**/*
  script:
  - Copy-Item "contrib/package.json" -Destination "."
  - Copy-Item "contrib/package-lock.json" -Destination "."
  - echo "Generate Changelog"
  - npx generate-changelog
  - Copy-Item "CHANGELOG.md" -Destination "build-tsan-dr791/package/doc/"
  - Copy-Item "CHANGELOG.md" -Destination "build-legacy-tsan-dr791/package/doc/"
  dependencies:
  - compile
  artifacts:
    paths:
    - build-tsan-dr791/package
    - build-legacy-tsan-dr791/package

