.globals: &globals
  tags:
  - windows
  - dynamorio

.testing: &testing
  variables:
    GIT_STRATEGY: "none"


variables:
  PROJECT_NAME: "DRace"
  GIT_SUBMODULE_STRATEGY: "normal"
  DRRUN_EXE: "C:\\opt\\DynamoRIO-Windows-7.91.18219-0\\bin64\\drrun.exe"
  _NT_SYMBOL_PATH: "SRV*c:\\symbolcache\\*https://msdl.microsoft.com/download/symbols"
  http_proxy: $CODE_PROXY
  https_proxy: $CODE_PROXY
  no_proxy: code.siemens.com,docker.siemens.com,devops.bt.siemens.com

stages:
  - inspect
  - build
  - test
  - package

### non architecture dependent tasks ###
cppcheck:
  <<: *globals
  stage: test
  script:
  - cd build-dr791;  C:\opt\Cppcheck\cppcheck.exe  --project=compile_commands.json --enable=all --inline-suppr --suppressions-list=suppressions.txt --error-exitcode=1 --quiet
  needs: ["windows_x64:compile"]

report-converter-test:
  stage: test
  tags:
    - AWS
  script:
  - echo "Start test..."
  - python3 tools/ReportConverter/ReportConverter.py -i tools/ReportConverter/test_files/helgrind.xml
  - python3 tools/ReportConverter/ReportConverter.py --Debug
  - python3 tools/ReportConverter/ReportConverterUnitTest.py

reuse-compliant:
  stage: inspect
  image: python:latest
  tags:
  - DOCKER
  before_script:
    - python3 -m venv ../venv
    - . ../venv/bin/activate
    - pip3 install fsfe-reuse
    - git clean -f -d
  script:
  - reuse lint

code-style:
  stage: inspect
  tags:
    - DOCKER
  image: ubuntu:18.04
  variables:
    GIT_SUBMODULE_STRATEGY: "none"
  script:
  - echo "Check code-style..."
  - apt-get update -y && apt-get install -y git clang-format
  - bash ./contrib/format-files.sh ci

### CMake + Build ###

windows_x64:compile:
  <<: *globals
  stage: build
  script:
  - echo "Release build..."
  - .\contrib\compile-win-x64.bat
  artifacts:
    paths:
    - build-dr791

linux_x64:compile:
  <<: *globals
  stage: build
  tags:
   - DOCKER
  image: docker.siemens.com/multicore/drace:buildamd64-ci
  script:
  - echo "Release build..."
  - if [ ! -d "DynamoRIO-x86_64-Linux-7.91.18271-0" ]; then wget https://github.com/DynamoRIO/dynamorio/releases/download/cronbuild-7.91.18271/DynamoRIO-x86_64-Linux-7.91.18271-0.tar.gz; fi
  - if [ ! -d "DynamoRIO-x86_64-Linux-7.91.18271-0" ]; then tar -xf DynamoRIO-x86_64-Linux-7.91.18271-0.tar.gz; fi
  - sh ./contrib/compile-linux-x64.sh
  cache:
    key: dynamorio-cache-x64
    paths:
      - ./DynamoRIO-x86_64-Linux-7.91.18271-0
  artifacts:
    paths:
    - build64

linux_i386:compile:
  <<: *globals
  stage: build
  tags:
   - DOCKER
  image: docker.siemens.com/multicore/drace:buildi386-ci
  script:
  - echo "Release build..."
  - if [ ! -d "DynamoRIO-i386-Linux-7.91.18271-0" ]; then wget https://github.com/DynamoRIO/dynamorio/releases/download/cronbuild-7.91.18271/DynamoRIO-i386-Linux-7.91.18271-0.tar.gz; fi
  - if [ ! -d "DynamoRIO-i386-Linux-7.91.18271-0" ]; then tar -xfDynamoRIO-i386-Linux-7.91.18271-0.tar.gz; fi
  - sh ./contrib/compile-linux-i386.sh
  cache:
    key: dynamorio-cache-i386
    paths:
      - ./DynamoRIO-i386-Linux-7.91.18271-0
  artifacts:
    paths:
    - build32

### Test ###

windows_x64:test:
  <<: *globals
  <<: *testing
  stage: test
  script:
  - cd build-dr791
  - echo "Use DR 7.91.x"
  # run only FT detector backend, as tsan often fails to alloc mem in low-memory environments
  - ctest -j4 -T test --output-on-failure -E "tsan"
  - ./bin/drace-system-tests.exe --gtest_output="xml:test-system-results.xml" --gtest_filter="*/0"
  artifacts:
    paths:
      - build-dr791/test-system-results.xml
      - build-dr791/Testing/**/Test.xml
    reports:
      junit:
      - build-dr791/test-system-results.xml
      - build-dr791/Testing/**/Test.xml
  needs: ["windows_x64:compile"]

#once the integration tests in linux are working, uncomment integration tests
linux_x64:test:
  <<: *globals
  <<: *testing
  stage: test
  tags:
   - DOCKER
  image: docker.siemens.com/multicore/drace:buildamd64-ci
  script:
  - echo "Use DR 7.91.x"
  - cd build64
  - ctest -j4 -T test --output-on-failure
  #- .\test\drace-system-tests --gtest_output="xml:test-system-results.xml"
  artifacts:
    paths:
    #- build64/test-system-results.xml
    - build64/Testing/**/Test.xml
    reports:
      junit:
      #- build64/test-system-results.xml
      - build64/Testing/**/Test.xml
  needs: ["linux_x64:compile"]

linux_i386:test:
  <<: *globals
  <<: *testing
  stage: test
  tags:
   - DOCKER
  image: docker.siemens.com/multicore/drace:buildi386-ci
  script:
  - echo "Use DR 7.91.x"
  - cd build32
  - ctest -j4 -T test --output-on-failure
  #- .\test\drace-system-tests --gtest_output="xml:test-system-results.xml"
  artifacts:
    paths:
    #- build32/test-system-results.xml
    - build32/Testing/**/Test.xml
    reports:
      junit:
      #- build32/test-system-results.xml
      - build32/Testing/**/Test.xml
  needs: ["linux_i386:compile"]

# Package
windows_x64:bundle:
  <<: *globals
  stage: package
  script:
  - Copy-Item "contrib/package.json" -Destination "."
  - Copy-Item "contrib/package-lock.json" -Destination "."
  - echo "Generate Changelog"
  - npx generate-changelog
  - Copy-Item "CHANGELOG.md" -Destination "build-dr791/package/doc/"
  needs: ["windows_x64:compile"]
  artifacts:
    paths:
    - build-dr791/package

pages:
  stage: package
  variables:
    GIT_STRATEGY: "none"
  needs: ["windows_x64:compile"]
  script:
    - mv build-dr791/doc/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master
